
# Site variables

title: TJCTF

# Jekyll config

encoding: utf-8
permalink: none

defaults:
    -
        values:
            layout: default

kramdown:
    auto_ids: true

sass:
    sass_dir: _sass

gems: [bourbon]
